"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=y(y=6f&6-*s)*0yvp=wx5ss_94ukpe044&gesp3^&u!(%wkn#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    # Channels 4.x 에서는 runserver 가 ASGI(WebSocket) 로 뜨려면 'daphne' 가
    # INSTALLED_APPS 최상단에 있어야 한다. 없으면 runserver 가 WSGI 로 떠서
    # /ws/ 요청이 일반 GET 으로 처리되어 404 → 프론트에서 "웹소켓 오류".
    'daphne',
    'channels',
    'playwright_job',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main.apps.MainConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'main.request_logging.RequestLogMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'main.context_processors.nav_home_url',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'
ASGI_APPLICATION = 'myproject.asgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    'workflow': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'main' / 'data' / 'workflow.db',
    },
    'reference': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('REFERENCE_PG_NAME', 'gscert_reference'),
        'USER': os.environ.get('REFERENCE_PG_USER', 'postgres'),
        'PASSWORD': os.environ.get('REFERENCE_PG_PASSWORD', ''),
        'HOST': os.environ.get('REFERENCE_PG_HOST', 'localhost'),
        'PORT': os.environ.get('REFERENCE_PG_PORT', '5432'),
    },
}

DATABASE_ROUTERS = [
    'main.db_routers.WorkflowDatabaseRouter',
    'main.db_routers.ReferenceDatabaseRouter',
]

WORKFLOW_DATABASE_ALIAS = 'workflow'
# 작업 실행 상태(잡/프로젝트/결과/로그/락)는 각 서버의 로컬 SQLite(workflow.db)에 둔다.
# 점검규칙(downloadreviewrule)은 두 서버가 공유하도록 주 서버의 PostgreSQL(reference)로 이전.
WORKFLOW_MODEL_NAMES = {
    'downloadreviewjob',
    'downloadreviewproject',
    'downloadreviewruleresult',
    'downloadreviewlog',
    'downloadreviewlock',
}

REFERENCE_DATABASE_ALIAS = 'reference'
# downloadreviewrule: 점검규칙을 주 서버 PostgreSQL에 단일 저장 → 194/241 공유, Django admin에서 수정.
REFERENCE_MODEL_NAMES = {'swdata', 'referencecenterpl', 'referenceproject', 'downloadreviewrule'}
DOWNLOAD_REVIEW_PROJECT_SOURCE = 'postgres'

# 로컬 점검 앱(local-review) API 인증 토큰.
# 값이 설정되면 /api/local-review/* 호출 시 헤더 X-Local-Review-Token 이 일치해야 한다.
# 비어 있으면(기본) 인증을 적용하지 않는다(기존 동작 유지 → 점진 도입 안전).
# 운영에서는 env.ps1 등으로 LOCAL_REVIEW_API_TOKEN 을 주입하고 사내 HTTPS와 함께 사용한다.
LOCAL_REVIEW_API_TOKEN = os.environ.get('LOCAL_REVIEW_API_TOKEN', '')

ECM_AGENT_LOCK_PATH = BASE_DIR / 'main' / 'data' / 'ecm_agent.lock'
ECM_AGENT_LOCK_TIMEOUT_SECONDS = 600
REFERENCE_DB_PATH = BASE_DIR / 'main' / 'data' / 'ecmlist.db'
REFERENCE_DB_PATH_2 = BASE_DIR / 'main' / 'data' / 'ecmlist2.db'
DOWNLOAD_REVIEW_ARTIFACT_DIR = BASE_DIR / 'main' / 'data' / 'download_review_artifacts'
REFERENCE_DB_TABLE = 'ecm_list'
# ── 서버 IP (설치 시 env.ps1 에서 주입; IP 하드코딩 금지) ──────────────
# MAIN_SERVER_IP : 주 서버 — PostgreSQL(reference+규칙) + 웹 네비게이션 홈 + download-review 전 센터 처리
# SUB_SERVER_IP  : (레거시) 서브 서버 — download-review 에서는 더 이상 쓰지 않고 194 로 넘긴다.
# FILE_SHARE_HOST: 산출물 보관용 공유 폴더 호스트
# 아래 기본값은 개발/기존 배포 호환용이며, 운영에서는 env.ps1 이 항상 덮어쓴다.
MAIN_SERVER_IP = os.environ.get('MAIN_SERVER_IP', '210.96.71.194')
SUB_SERVER_IP = os.environ.get('SUB_SERVER_IP', '210.96.71.241')
FILE_SHARE_HOST = os.environ.get('FILE_SHARE_HOST', '210.96.71.99')

# HTTPS(nginx TLS) 도입에 따른 CSRF 신뢰 출처. Django 4+ 는 POST 시 Origin/Referer 를
# 이 목록과 대조하므로, 서버 IP 의 http/https 를 모두 등록해야 https 화면의 POST(이력 검색,
# 다운로드 검토 등)가 403 나지 않는다. (ALLOWED_HOSTS='*' 여도 CSRF 는 별도로 필요)
CSRF_TRUSTED_ORIGINS = [
    f'{scheme}://{host}'
    for host in {MAIN_SERVER_IP, SUB_SERVER_IP, '127.0.0.1', 'localhost'}
    for scheme in ('https', 'http')
]
# nginx 가 X-Forwarded-Proto 를 넘기므로 Django 가 https 요청을 https 로 인식하게 한다.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# 194 단일화: ECM HTTP 직접연동으로 194 가 모든 센터의 ECM(분당 210.104.181.10 / 상암·영남
# 210.96.71.85)에 직접 접속할 수 있으므로, download-review 웹/API/워커를 194 한 서버가
# 분당·상암·영남 세 센터 모두 처리한다. 241 은 download-review 에서 제외(모든 요청을 194 로 보냄).
# 주의: 194 워커는 반드시 source=ecm-http 로 떠 있어야 상암/영남을 처리할 수 있다
# (Playwright 방식은 194 에 상암/영남 브라우저 환경이 없다).
DOWNLOAD_REVIEW_DEFAULT_CENTER = 'bundang'
DOWNLOAD_REVIEW_DEFAULT_CENTER_BY_HOST = {
    MAIN_SERVER_IP: 'bundang',
    SUB_SERVER_IP: 'bundang',
}
DOWNLOAD_REVIEW_ALLOWED_CENTERS_BY_HOST = {
    MAIN_SERVER_IP: {'bundang', 'sangam', 'yeongnam'},
    SUB_SERVER_IP: {'bundang', 'sangam', 'yeongnam'},
}
DOWNLOAD_REVIEW_WORKER_CENTERS = {
    value.strip()
    for value in os.environ.get('DOWNLOAD_REVIEW_WORKER_CENTERS', '').split(',')
    if value.strip()
}
DOWNLOAD_REVIEW_CENTER_ROUTES_BY_HOST = {
    MAIN_SERVER_IP: {   # 194: 세 센터 모두 로컬 처리(리다이렉트 없음)
        'bundang': '',
        'sangam': '',
        'yeongnam': '',
    },
    SUB_SERVER_IP: {    # 241: download-review 제외 → 모든 센터를 194 로 넘긴다
        'bundang': f'http://{MAIN_SERVER_IP}/download-review/',
        'sangam': f'http://{MAIN_SERVER_IP}/download-review/',
        'yeongnam': f'http://{MAIN_SERVER_IP}/download-review/',
    },
}
DOWNLOAD_REVIEW_TIME_ZONE = 'Asia/Seoul'
# TODO(TEST_ONLY_DOWNLOAD_REVIEW_TIME_WINDOW):
# 라이브 검증 중에는 0~24 전체 시간 허용. 테스트 완료 즉시 START_HOUR=20, END_HOUR=7로 되돌린다.
DOWNLOAD_REVIEW_IGNORE_TIME_WINDOW = False
DOWNLOAD_REVIEW_START_HOUR = 0
DOWNLOAD_REVIEW_END_HOUR = 24
DOWNLOAD_REVIEW_ACTIVE_JOB_LIMIT = 5
DOWNLOAD_REVIEW_MAX_PROJECTS_PER_JOB = 100
DOWNLOAD_REVIEW_NAV_HOME_BY_HOST = {
    MAIN_SERVER_IP: '',                          # 메인(분당)이 웹 네비게이션 홈
    SUB_SERVER_IP: f'http://{MAIN_SERVER_IP}',   # 서브(상암/영남)는 메인으로 리다이렉트
}
# 점검규칙은 주 서버 PostgreSQL(reference)에 단일 저장되어 두 서버가 공유한다.
# 서브 서버는 REFERENCE_PG_HOST 가 주 서버를 가리키므로 동일 규칙을 직접 읽는다.
# (과거의 HTTP 번들 동기화 방식은 제거됨.)

# --- ECM 다운로드 자동화 설정 ---
ECM_BASE_URL = os.environ.get('ECM_BASE_URL', 'http://210.96.71.85')
ECM_BASE_URL_BUNDANG = os.environ.get('ECM_BASE_URL_BUNDANG', 'http://210.104.181.10')
# HTTP 직접연동(ecm-http) 자격증명 — 코드/DB 에 평문 저장 금지, 환경변수로만 주입.
# 상암·영남 공유 계정 / 분당 별도 계정. (main/docs/34_http_ecm_source_decisions.md 결정 1)
ECM_USERNAME = os.environ.get('ECM_USERNAME', '')
ECM_PASSWORD = os.environ.get('ECM_PASSWORD', '')
ECM_USERNAME_BUNDANG = os.environ.get('ECM_USERNAME_BUNDANG', '')
ECM_PASSWORD_BUNDANG = os.environ.get('ECM_PASSWORD_BUNDANG', '')
# HTTP 직접연동 트리 탐색 시작 root OID(센터별). 미설정 시 센터 정의 기본값 사용.
ECM_ROOT_OID_SANGAM = os.environ.get('ECM_ROOT_OID_SANGAM', '')
ECM_ROOT_OID_YEONGNAM = os.environ.get('ECM_ROOT_OID_YEONGNAM', '')
ECM_ROOT_OID_BUNDANG = os.environ.get('ECM_ROOT_OID_BUNDANG', '')
ECM_BROWSER_CHANNEL = os.environ.get('ECM_BROWSER_CHANNEL', '')
ECM_BROWSER_ARGS = [
    arg.strip()
    for arg in os.environ.get(
        'ECM_BROWSER_ARGS',
        '--disable-features=LocalNetworkAccessChecks,BlockInsecurePrivateNetworkRequests,PrivateNetworkAccessSendPreflights,PrivateNetworkAccessRespectPreflightResults --disable-local-network-access-check',
    ).split()
    if arg.strip()
]
ECM_TREE_ROOT_INDEX = int(os.environ.get('ECM_TREE_ROOT_INDEX', '0'))
ECM_TREE_ROOT_INDEX_BUNDANG = int(os.environ.get('ECM_TREE_ROOT_INDEX_BUNDANG', '0'))
ECM_TREE_ROOT_INDEX_YEONGNAM = int(os.environ.get('ECM_TREE_ROOT_INDEX_YEONGNAM', '0'))
AGENT_DOWNLOAD_BASE_DIR = os.environ.get(
    'AGENT_DOWNLOAD_BASE_DIR',
    str(Path.home() / 'download'),
)
# 산출물 source 선택: 'ecm'(Playwright, 현 운영 기본) / 'ecm-http'(서버 HTTP 직접연동)
# / 'local'(LOCAL_ARTIFACT_SOURCE_ROOT 에서 복사, ECM 없이 워커 흐름을 돌리는 fake-live).
# 'ecm-http' 는 requests 로 ECM 을 직접 호출하며 Playwright/pywinauto 가 필요 없다.
# 안정화 후 기본값을 'ecm-http' 로 전환한다. 자세한 내용은
# main/docs/33_artifact_source_boundary.md, main/docs/34_http_ecm_source_decisions.md 참고.
DOWNLOAD_REVIEW_SOURCE = os.environ.get('DOWNLOAD_REVIEW_SOURCE', 'ecm')
LOCAL_ARTIFACT_SOURCE_ROOT = os.environ.get('LOCAL_ARTIFACT_SOURCE_ROOT', '')
AGENT_ARCHIVE_BASE_DIR = os.environ.get(
    'AGENT_ARCHIVE_BASE_DIR',
    rf'\\{FILE_SHARE_HOST}\ecm',
)
ECM_DOWNLOAD_TIMEOUTS = {
    'GOTO': 15_000,
    'FOLDER_SEARCH': 10_000,
    'DOC_LIST': 10_000,
    'MENU_VISIBLE': 5_000,
    'SPLASH': 10_000,
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'plain': {
            'format': '%(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'plain',
        },
    },
    'loggers': {
        'gscert.request': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

STATICFILES_DIRS = [
    BASE_DIR / "main/static",  # ?먮뒗 BASE_DIR / "static"
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_REDIRECT_URL = '/welcome/'
