"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=y(y=6f&6-*s)*0yvp=wx5ss_94ukpe044&gesp3^&u!(%wkn#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'channels',
    'playwright_job',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main.apps.MainConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'
ASGI_APPLICATION = 'myproject.asgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    'workflow': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'main' / 'data' / 'workflow.db',
    }
}

DATABASE_ROUTERS = [
    'main.db_routers.WorkflowDatabaseRouter',
]

WORKFLOW_DATABASE_ALIAS = 'workflow'
WORKFLOW_MODEL_NAMES = {
    'downloadreviewjob',
    'downloadreviewproject',
    'downloadreviewrule',
    'downloadreviewruleresult',
    'downloadreviewlog',
    'downloadreviewlock',
}

ECM_AGENT_LOCK_PATH = BASE_DIR / 'main' / 'data' / 'ecm_agent.lock'
ECM_AGENT_LOCK_TIMEOUT_SECONDS = 600
REFERENCE_DB_PATH = BASE_DIR / 'main' / 'data' / 'ecmlist.db'
REFERENCE_DB_TABLE = 'ecm_list'
DOWNLOAD_REVIEW_TIME_ZONE = 'Asia/Seoul'
DOWNLOAD_REVIEW_START_HOUR = 20
DOWNLOAD_REVIEW_END_HOUR = 7
DOWNLOAD_REVIEW_ACTIVE_JOB_LIMIT = 5
DOWNLOAD_REVIEW_MAX_PROJECTS_PER_JOB = 100

# --- ECM 다운로드 자동화 설정 ---
ECM_BASE_URL = os.environ.get('ECM_BASE_URL', 'http://210.96.71.85')
AGENT_DOWNLOAD_BASE_DIR = os.environ.get(
    'AGENT_DOWNLOAD_BASE_DIR',
    str(Path.home() / 'Downloads'),
)
ECM_DOWNLOAD_TIMEOUTS = {
    'GOTO': 15_000,
    'FOLDER_SEARCH': 10_000,
    'DOC_LIST': 10_000,
    'MENU_VISIBLE': 5_000,
    'SPLASH': 10_000,
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    BASE_DIR / "main/static",  # ?먮뒗 BASE_DIR / "static"
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_REDIRECT_URL = '/welcome/'
