"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=y(y=6f&6-*s)*0yvp=wx5ss_94ukpe044&gesp3^&u!(%wkn#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'channels',
    'playwright_job',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main.apps.MainConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'main.request_logging.RequestLogMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'main.context_processors.nav_home_url',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'
ASGI_APPLICATION = 'myproject.asgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    'workflow': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'main' / 'data' / 'workflow.db',
    },
    'reference': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('REFERENCE_PG_NAME', 'gscert_reference'),
        'USER': os.environ.get('REFERENCE_PG_USER', 'postgres'),
        'PASSWORD': os.environ.get('REFERENCE_PG_PASSWORD', ''),
        'HOST': os.environ.get('REFERENCE_PG_HOST', 'localhost'),
        'PORT': os.environ.get('REFERENCE_PG_PORT', '5432'),
    },
}

DATABASE_ROUTERS = [
    'main.db_routers.WorkflowDatabaseRouter',
    'main.db_routers.ReferenceDatabaseRouter',
]

WORKFLOW_DATABASE_ALIAS = 'workflow'
WORKFLOW_MODEL_NAMES = {
    'downloadreviewjob',
    'downloadreviewproject',
    'downloadreviewrule',
    'downloadreviewruleresult',
    'downloadreviewlog',
    'downloadreviewlock',
}

REFERENCE_DATABASE_ALIAS = 'reference'
REFERENCE_MODEL_NAMES = {'swdata', 'referencecenterpl', 'referenceproject'}
DOWNLOAD_REVIEW_PROJECT_SOURCE = 'postgres'

ECM_AGENT_LOCK_PATH = BASE_DIR / 'main' / 'data' / 'ecm_agent.lock'
ECM_AGENT_LOCK_TIMEOUT_SECONDS = 600
REFERENCE_DB_PATH = BASE_DIR / 'main' / 'data' / 'ecmlist.db'
REFERENCE_DB_PATH_2 = BASE_DIR / 'main' / 'data' / 'ecmlist2.db'
DOWNLOAD_REVIEW_ARTIFACT_DIR = BASE_DIR / 'main' / 'data' / 'download_review_artifacts'
REFERENCE_DB_TABLE = 'ecm_list'
DOWNLOAD_REVIEW_DEFAULT_CENTER = 'sangam'
DOWNLOAD_REVIEW_DEFAULT_CENTER_BY_HOST = {
    '210.96.71.194': 'bundang',
    '210.96.71.241': 'sangam',
}
DOWNLOAD_REVIEW_ALLOWED_CENTERS_BY_HOST = {
    '210.96.71.194': {'bundang'},
    '210.96.71.241': {'sangam', 'yeongnam'},
}
DOWNLOAD_REVIEW_WORKER_CENTERS = {
    value.strip()
    for value in os.environ.get('DOWNLOAD_REVIEW_WORKER_CENTERS', '').split(',')
    if value.strip()
}
DOWNLOAD_REVIEW_CENTER_ROUTES_BY_HOST = {
    '210.96.71.194': {
        'bundang': '',
        'sangam': 'http://210.96.71.241/download-review/',
        'yeongnam': 'http://210.96.71.241/download-review/',
    },
    '210.96.71.241': {
        'bundang': 'http://210.96.71.194/download-review/',
        'sangam': '',
        'yeongnam': '',
    },
}
DOWNLOAD_REVIEW_TIME_ZONE = 'Asia/Seoul'
# TODO(TEST_ONLY_DOWNLOAD_REVIEW_TIME_WINDOW):
# 라이브 검증 중에는 0~24 전체 시간 허용. 테스트 완료 즉시 START_HOUR=20, END_HOUR=7로 되돌린다.
DOWNLOAD_REVIEW_IGNORE_TIME_WINDOW = False
DOWNLOAD_REVIEW_START_HOUR = 0
DOWNLOAD_REVIEW_END_HOUR = 24
DOWNLOAD_REVIEW_ACTIVE_JOB_LIMIT = 5
DOWNLOAD_REVIEW_MAX_PROJECTS_PER_JOB = 100
DOWNLOAD_REVIEW_NAV_HOME_BY_HOST = {
    '210.96.71.194': '',
    '210.96.71.241': 'http://210.96.71.194',
}

# --- ECM 다운로드 자동화 설정 ---
ECM_BASE_URL = os.environ.get('ECM_BASE_URL', 'http://210.96.71.85')
ECM_BROWSER_CHANNEL = os.environ.get('ECM_BROWSER_CHANNEL', '')
ECM_BROWSER_ARGS = [
    arg.strip()
    for arg in os.environ.get(
        'ECM_BROWSER_ARGS',
        '--disable-features=LocalNetworkAccessChecks,BlockInsecurePrivateNetworkRequests,PrivateNetworkAccessSendPreflights,PrivateNetworkAccessRespectPreflightResults --disable-local-network-access-check',
    ).split()
    if arg.strip()
]
ECM_TREE_ROOT_INDEX = int(os.environ.get('ECM_TREE_ROOT_INDEX', '0'))
ECM_TREE_ROOT_INDEX_BUNDANG = int(os.environ.get('ECM_TREE_ROOT_INDEX_BUNDANG', '0'))
ECM_TREE_ROOT_INDEX_YEONGNAM = int(os.environ.get('ECM_TREE_ROOT_INDEX_YEONGNAM', '0'))
AGENT_DOWNLOAD_BASE_DIR = os.environ.get(
    'AGENT_DOWNLOAD_BASE_DIR',
    str(Path.home() / 'Downloads'),
)
AGENT_ARCHIVE_BASE_DIR = os.environ.get(
    'AGENT_ARCHIVE_BASE_DIR',
    r'\\210.96.71.99\ecm',
)
ECM_DOWNLOAD_TIMEOUTS = {
    'GOTO': 15_000,
    'FOLDER_SEARCH': 10_000,
    'DOC_LIST': 10_000,
    'MENU_VISIBLE': 5_000,
    'SPLASH': 10_000,
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'plain': {
            'format': '%(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'plain',
        },
    },
    'loggers': {
        'gscert.request': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

STATICFILES_DIRS = [
    BASE_DIR / "main/static",  # ?먮뒗 BASE_DIR / "static"
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_REDIRECT_URL = '/welcome/'
