# Generated by Django 5.2.14 on 2026-05-12 01:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadReviewRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('target_file_pattern', models.CharField(blank=True, max_length=255)),
                ('target_file_type', models.CharField(default='any', max_length=30)),
                ('rule_type', models.CharField(blank=True, max_length=80)),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('severity', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning'), ('info', 'Info')], default='error', max_length=20)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('version', models.CharField(default='1', max_length=40)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inspection_rule',
                'ordering': ['sort_order', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('final_link', models.URLField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DownloadReviewJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, default='scheduled', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('available_after', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('progress_message', models.CharField(blank=True, max_length=500)),
                ('requested_project_count', models.PositiveIntegerField(default=0)),
                ('completed_project_count', models.PositiveIntegerField(default=0)),
                ('failed_project_count', models.PositiveIntegerField(default=0)),
                ('selected_projects_json', models.JSONField(blank=True, default=list)),
                ('requested_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_error_message', models.TextField(blank=True)),
                ('worker_pid', models.PositiveIntegerField(blank=True, null=True)),
                ('worker_host', models.CharField(blank=True, max_length=255)),
                ('worker_heartbeat_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'automation_job',
                'ordering': ['requested_at', 'id'],
                'indexes': [models.Index(fields=['status', 'requested_at'], name='dr_job_status_req_idx'), models.Index(fields=['available_after'], name='dr_job_available_idx')],
            },
        ),
        migrations.CreateModel(
            name='DownloadReviewLock',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('locked', models.BooleanField(default=False)),
                ('owner', models.CharField(blank=True, max_length=80)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locks', to='main.downloadreviewjob')),
            ],
            options={
                'db_table': 'automation_lock',
            },
        ),
        migrations.CreateModel(
            name='DownloadReviewProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_number', models.CharField(db_index=True, max_length=32)),
                ('ecm_row_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('downloaded', 'Downloaded'), ('inspecting', 'Inspecting'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='queued', max_length=20)),
                ('review_status', models.CharField(choices=[('unreviewed', 'Unreviewed'), ('completed', 'Completed'), ('needs_fix', 'Needs fix'), ('held', 'Held')], db_index=True, default='unreviewed', max_length=20)),
                ('download_dir', models.TextField(blank=True)),
                ('zip_path', models.TextField(blank=True)),
                ('zip_file_name', models.CharField(blank=True, max_length=255)),
                ('zip_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('current_step', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('error_detail', models.TextField(blank=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='main.downloadreviewjob')),
            ],
            options={
                'db_table': 'automation_job_project',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DownloadReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], db_index=True, default='info', max_length=20)),
                ('event_code', models.CharField(blank=True, max_length=80)),
                ('message', models.TextField()),
                ('detail_json', models.JSONField(blank=True, default=dict)),
                ('admin_only', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='main.downloadreviewjob')),
                ('job_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='main.downloadreviewproject')),
            ],
            options={
                'db_table': 'automation_log',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DownloadReviewRuleResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_code', models.CharField(blank=True, max_length=80)),
                ('rule_name', models.CharField(max_length=255)),
                ('sequence', models.PositiveSmallIntegerField(default=0)),
                ('file_path', models.TextField(blank=True)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('warning', 'Warning'), ('error', 'Error')], db_index=True, max_length=20)),
                ('expected', models.TextField(blank=True)),
                ('actual', models.TextField(blank=True)),
                ('message', models.TextField(blank=True)),
                ('raw_detail_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_results', to='main.downloadreviewproject')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='main.downloadreviewrule')),
            ],
            options={
                'db_table': 'inspection_result',
                'ordering': ['job_project', 'sequence', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='downloadreviewproject',
            index=models.Index(fields=['job', 'status'], name='dr_project_job_status_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadreviewproject',
            index=models.Index(fields=['project_number'], name='dr_project_number_idx'),
        ),
        migrations.AddConstraint(
            model_name='downloadreviewproject',
            constraint=models.UniqueConstraint(fields=('job', 'project_number'), name='dr_project_job_number_uniq'),
        ),
        migrations.AddIndex(
            model_name='downloadreviewlog',
            index=models.Index(fields=['job', 'created_at'], name='dr_log_job_created_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadreviewlog',
            index=models.Index(fields=['job_project', 'created_at'], name='dr_log_project_created_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadreviewruleresult',
            index=models.Index(fields=['job_project', 'status'], name='dr_rule_result_status_idx'),
        ),
    ]
