# Generated by Codex on 2026-05-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="downloadreviewjob",
            name="center_code",
            field=models.CharField(db_index=True, default="sangam", max_length=20),
        ),
        migrations.AddField(
            model_name="downloadreviewproject",
            name="center_code",
            field=models.CharField(db_index=True, default="sangam", max_length=20),
        ),
        migrations.AddIndex(
            model_name="downloadreviewjob",
            index=models.Index(fields=["center_code", "status"], name="dr_job_center_status_idx"),
        ),
        migrations.AddIndex(
            model_name="downloadreviewproject",
            index=models.Index(fields=["center_code", "project_number"], name="dr_project_center_number_idx"),
        ),
    ]
