# Generated by Django 5.2.15 on 2026-06-26 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_reference_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadreviewruleresult',
            name='rule',
        ),
    ]
