# Generated by Django 5.2.15 on 2026-07-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_move_rule_to_reference_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='swdata',
            name='prev_cert_info',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='swdata',
            name='recert_type',
            field=models.TextField(blank=True, default=''),
        ),
    ]
