# Generated by Django 5.2.15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_swdata_prev_cert_info_swdata_recert_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='swdata',
            name='kolas',
            field=models.TextField(blank=True, default=''),
        ),
    ]
